import { useLocation, useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowLeft, Brain, CheckCircle, Download, RefreshCw, Sparkles, FileText } from 'lucide-react'
import toast from 'react-hot-toast'
import { useAuthContext } from '../context/AuthContext.jsx'
import DocumentStats from '../components/DocumentStats.jsx'
import SummaryPanel from '../components/SummaryPanel.jsx'
import KeyInsights from '../components/KeyInsights.jsx'
import ImprovementSuggestions from '../components/ImprovementSuggestions.jsx'
import DocumentViewer from '../components/DocumentViewer.jsx'

export default function Analysis() {
  const { state } = useLocation()
  const navigate = useNavigate()
  const { user } = useAuthContext()

  const initials = (user?.user_metadata?.full_name || user?.email || 'U')
    .split(' ').map(n => n[0]).slice(0, 2).join('').toUpperCase()

  // Guard: redirect if arrived without data
  if (!state?.result) {
    navigate('/')
    return null
  }

  const { result, filename } = state

  const handleDownloadFullReport = () => {
    const report = [
      `# DocuMind AI Document Intelligence Report`,
      `**Document:** ${filename || result.document.name}`,
      `**Type:** ${result.document.type} | **Pages:** ${result.document.pages} | **Words:** ${result.document.word_count.toLocaleString()} | **Language:** ${result.document.language}`,
      `**Extraction Method:** ${result.extraction.method} (Confidence: ${Math.round(result.extraction.confidence * 100)}%)`,
      `\n---\n`,
      `## 1. Executive Summary`,
      result.summary.executive,
      `\n## 2. Standard Summary`,
      result.summary.standard,
      `\n## 3. Detailed Summary`,
      result.summary.detailed,
      `\n---\n`,
      `## 4. Key Actionable Insights`,
      ...result.key_insights.map((item, i) => `${i + 1}. ${item.text}${item.source_page ? ` (Source: Page ${item.source_page})` : ''}`),
      `\n---\n`,
      `## 5. Quality Score Metrics`,
      `- Clarity: ${result.quality.clarity}%`,
      `- Structure: ${result.quality.structure}%`,
      `- Completeness: ${result.quality.completeness}%`,
      `- Overall Score: ${result.quality.overall}%`,
      `\n---\n`,
      `## 6. AI Improvement Suggestions`,
      ...result.improvements.map((item) => `- [${item.category}] **${item.message}**: ${item.suggestion}`),
      `\n---\n`,
      `Generated by DocuMind AI Platform`,
    ].join('\n\n')

    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${(filename || 'DocuMind-Analysis').replace(/\.[^/.]+$/, '')}-Report.md`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Full Markdown report downloaded!')
  }

  return (
    <div className="min-h-screen flex flex-col">
      {/* Nav */}
      <nav className="border-b border-surface-border px-6 py-4 flex items-center justify-between sticky top-0 bg-surface/90 backdrop-blur-sm z-10">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate('/')}
            className="btn-ghost flex items-center gap-1.5 -ml-2"
          >
            <ArrowLeft size={16} />
            Back
          </button>
          <div className="w-px h-5 bg-surface-border" />
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-brand-600 flex items-center justify-center">
              <Brain size={12} className="text-white" />
            </div>
            <span className="font-semibold text-sm">DocuMind</span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleDownloadFullReport}
            className="btn-ghost flex items-center gap-1.5 text-xs text-brand-300 hover:text-brand-200 border border-surface-border py-1.5 px-3 rounded-lg"
          >
            <Download size={13} />
            <span className="hidden sm:inline">Export Report (.md)</span>
          </button>
          <button
            onClick={() => navigate('/')}
            className="btn-primary flex items-center gap-1.5 text-xs py-1.5 px-3"
          >
            <RefreshCw size={12} />
            <span className="hidden sm:inline">New Document</span>
          </button>
          <button
            onClick={() => navigate('/profile')}
            className="w-8 h-8 rounded-full bg-brand-600 flex items-center justify-center
                       text-white text-xs font-bold hover:bg-brand-500 transition-colors ml-1"
            title="Profile"
          >
            {initials}
          </button>
        </div>
      </nav>

      {/* Main content */}
      <main className="flex-1 px-4 sm:px-6 py-8 max-w-7xl mx-auto w-full">
        {/* Page header */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-8"
        >
          <div className="flex flex-wrap items-center gap-2 mb-1.5">
            <span className="badge bg-brand-900/60 text-brand-300 text-xs font-semibold flex items-center gap-1">
              <Sparkles size={11} /> AI Analysis Complete
            </span>
            <span className="badge bg-surface text-slate-400 text-xs">
              {result.document.type}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-100 truncate">
            {filename || result.document.name}
          </h1>
          <p className="text-slate-400 text-sm mt-1.5">
            {result.document.pages} page{result.document.pages === 1 ? '' : 's'} · {result.document.word_count.toLocaleString()} words · {result.document.language} language · {result.extraction.method === 'ocr' ? 'Gemini AI Vision OCR' : 'Native PDF Parsing'}
          </p>
        </motion.div>

        {/* Top row: stats + summary */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
          <div className="lg:col-span-1">
            <DocumentStats
              document={result.document}
              extraction={result.extraction}
            />
          </div>
          <div className="lg:col-span-2">
            <SummaryPanel summary={result.summary} />
          </div>
        </div>

        {/* Middle row: key insights + improvements */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-6">
          <KeyInsights insights={result.key_insights} />
          <ImprovementSuggestions
            improvements={result.improvements}
            quality={result.quality}
          />
        </div>

        {/* Bottom: Document Explorer */}
        <DocumentViewer
          fullText={result.full_text}
          sections={result.sections}
        />
      </main>
    </div>
  )
}
